"""Log frequency/duration pairs generated by the ORIGINAL BASIC PLAY parser.
Hooks its SOUND queue entry; no approximation of PLAY syntax is made here.
A copy is modified in a temporary directory. Durations are 2048 PIT clocks.
"""
from pathlib import Path
import os,struct,subprocess,tempfile,json
ROOT=Path(__file__).resolve().parents[1];BASE=5662;HEADER=5632;RUNTIME=17600
SONGS={
 'intro':'mbt190o2l8bbbl16cecl8bbp8bbbl16cl8edcc',
 'dot':'t255mbl64o1afgao4d',
 'power':'mbl64abceabceebceabceagaa',
 'death':'mbl8t255o4fego3abcdefgo0l1g-g',
 'eat':'mbl24o2cc#dd#eff#gg#aa#bl32o3cc#dd#eff#gg#aa#bl64o4cc#dd#eff#gg#aa#b',
 'wall':(4000,0xb4e),'floor':(150,0xb5a)
}
def capture(sequence):
 b=bytearray((ROOT/'original/pac-gal/Pac-gal.05.1982.exe').read_bytes());patches=[];extra=[]
 def patch(pos,data):
  b[pos:pos+len(data)]=data;patches.append((pos,pos+len(data)))
 def game(pos,data):patch(BASE+pos,data)
 def jump(pos,dest):game(pos,b'\xe9'+struct.pack('<h',dest-pos-3))
 jump(0x19,0x47);jump(0x6d,0x22e);jump(0x2e4,0x1fcf)
 # Record entry arguments while executing the original queue code unchanged.
 hook=RUNTIME+0x1eee;tramp=0x4500
 patch(hook,b'\xe9'+struct.pack('<h',tramp-0x1ef1)+b'\x90'*3)
 body=b'\x9a'+struct.pack('<HH',0x83+30,0)
 extra.append((RUNTIME+tramp+3-HEADER,0))
 body+=b'\xe8'+struct.pack('<h',0x1f81-(tramp+8))+bytes.fromhex('86f252')
 body+=b'\xe9'+struct.pack('<h',0x1ef4-(tramp+len(body)+3))
 patch(RUNTIME+tramp,body)
 trace=bytes.fromhex('50 57 2e8b3ef004 2e898d0005 2e89950205 83c704 2e893ef004 5f58cb')
 game(0x83,trace)
 # Zero the log and install its DOS filename inside unused maze code.
 patch(HEADER+0x4e0,b'AUDIO.BIN\x00');patch(HEADER+0x4f0,b'\x00\x00')
 code=bytearray();pos=0x1fcf
 def word(addr,value):code.extend(b'\xc7\x06'+struct.pack('<HH',addr,value&65535))
 def far(offset):
  here=BASE+pos+len(code);code.extend(b'\x9a'+struct.pack('<HH',offset,0x2ec));extra.append((here+3-HEADER,0))
 for j in range(0,10,2):word(0xa30+j,int.from_bytes(b'AUDIO.BIN\0'[j:j+2],'little'))
 code.extend(bytes.fromhex('ba300a31c9b43ccd21a3240a'));word(0xa28,0x1234)
 for item in sequence:
  song=SONGS[item] if item in SONGS else item
  if isinstance(song,str):
   raw=song.encode('ascii');word(0xa16,len(raw));word(0xa18,0xe00)
   for i in range(0,len(raw),2):word(0xe00+i,int.from_bytes(raw[i:i+2].ljust(2,b'\0'),'little'))
   code.extend(bytes.fromhex('bb160a'));far(0x249d)
  else:
   hz,duration=song;code.extend(b'\xbb'+struct.pack('<H',hz)+b'\xba'+struct.pack('<H',duration));far(0x1eba)
 # Switch DS to CS for the log, create file, write and exit DOS.
 code.extend(bytes.fromhex('8b1e240a 0e1f ba0005 8b0ef004 b440 cd21 b8004c cd21'))
 assert pos+len(code)<0x2800
 game(pos,code)
 rel=[]
 for i in range(struct.unpack_from('<H',b,6)[0]):
  off,seg=struct.unpack_from('<HH',b,28+i*4);a=HEADER+seg*16+off
  if not any(lo<=a<hi for lo,hi in patches):rel.append((off,seg))
 rel+=extra;struct.pack_into('<H',b,6,len(rel))
 for i,r in enumerate(rel):struct.pack_into('<HH',b,28+i*4,*r)
 with tempfile.TemporaryDirectory(prefix='pacgal-audio-') as tmp:
  Path(tmp,'AUDIO.EXE').write_bytes(b)
  dump=bytearray.fromhex('0e1f ba0000 31c9 b43c cd21 89c3 b800b8 8ed8 31d2 b9a00f b440 cd21 b8004c cd21')
  struct.pack_into('<H',dump,3,0x100+len(dump));dump+=b'SCREEN.BIN\0';Path(tmp,'DUMP.COM').write_bytes(dump)
  env=dict(os.environ,SDL_VIDEODRIVER='dummy',SDL_AUDIODRIVER='dummy')
  subprocess.run(['dosbox','-c',f'mount c {tmp}','-c','c:','-c','AUDIO.EXE','-c','DUMP.COM','-c','exit'],env=env,check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL,timeout=20)
  if not Path(tmp,'AUDIO.BIN').exists():raise RuntimeError('Audio oracle failed; files: '+str([(p.name,p.stat().st_size) for p in Path(tmp).iterdir()]))
  data=Path(tmp,'AUDIO.BIN').read_bytes()
  if not data or len(data)%4:raise RuntimeError('Invalid or empty audio log from original DOS parser')
  return [list(x) for x in struct.iter_unpack('<HH',data)]
if __name__=='__main__':
 fixtures={}
 for name in SONGS:
  notes=capture([name]);fixtures[name]=notes
  print(name,len(notes),notes[:8],flush=True)
 fixtures['sequence']=capture(['intro','dot','power','wall','floor','death','eat'])
 (ROOT/'docs/audio-oracle.json').write_text(json.dumps(fixtures,indent=2)+'\n')
